// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL = Session pooler (port 5432) — podržava prepared statements za migracije.
    // Runtime app koristi DATABASE_URL preko PrismaPg adaptera u src/lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
